# Generated by Django 4.0.2 on 2022-03-12 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0003_remove_cart_item_cart_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='item',
            field=models.ManyToManyField(to='e_commerce.Item'),
        ),
    ]
