# Generated by Django 4.0.2 on 2022-03-12 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0004_alter_cart_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default='logo.svg', null=True, upload_to=''),
        ),
    ]
