# Generated by Django 4.0.2 on 2022-03-14 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0007_favlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='fav_id',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
