# Generated by Django 4.0.2 on 2022-03-15 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0010_remove_favlist_creator_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='creator_id',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
