# Generated by Django 4.0.2 on 2022-03-16 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0011_item_creator_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='guest', max_length=10)),
                ('email', models.EmailField(max_length=150, null=True)),
                ('address1', models.CharField(default='anddress 1', max_length=1024)),
                ('address2', models.CharField(default='anddress 2', max_length=1024)),
                ('zip_code', models.IntegerField(default=99999, null=True)),
                ('city', models.CharField(default='city', max_length=150)),
                ('country', models.CharField(default='country', max_length=50)),
            ],
        ),
    ]
