# Generated by Django 4.0.2 on 2022-03-16 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0013_shipping_ship_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='email',
            field=models.EmailField(default='guest@email.com', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='zip_code',
            field=models.IntegerField(null=True),
        ),
    ]
