# Generated by Django 4.0.2 on 2022-03-16 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0014_alter_shipping_email_alter_shipping_zip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='address1',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='address2',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='city',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='country',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='email',
            field=models.EmailField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='name',
            field=models.CharField(max_length=10),
        ),
    ]
