# Generated by Django 4.0.2 on 2022-03-17 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0016_alter_shipping_zip_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipping',
            old_name='address1',
            new_name='address_1',
        ),
    ]
