# Generated by Django 4.0.2 on 2022-03-17 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0017_rename_address1_shipping_address_1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipping',
            old_name='address2',
            new_name='address_2',
        ),
    ]
