# Generated by Django 4.0.2 on 2022-03-18 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0021_order_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shipping',
        ),
        migrations.DeleteModel(
            name='Shipping',
        ),
    ]
